version: "3"

services:
  neo4j:
    image: convivio/neo4j:$NEO4J_TAG
    container_name: "${PROJECT_NAME}_neo4j"
    volumes: 
      - graph-data:/data
      - graph-logs:/logs
      - ./neo4j/import:/import
    ports:
      - '7474:7474'
      # - '7473:7473'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/$NEO4J_PASSWORD
      - NEO4J_HOST=$NEO4J_HOST
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      # NEO4J_BOLT_PORT_NUMBER: $NEO4J_BOLT_PORT_NUMBER
      # NEO4J_HTTP_PORT_NUMBER: $NEO4J_HTTP_PORT_NUMBER
      # NEO4J_HTTPS_PORT_NUMBER: $NEO4J_HTTPS_PORT_NUMBER
    networks:
      - graph
      - traefik
    labels:
      - 'traefik.backend=neo4j'
      - 'traefik.port=$NEO4J_HTTP_PORT_NUMBER'
      - 'traefik.frontend.rule=Host:graph.${PROJECT_BASE_URL}'
      - 'traefik.docker.network=traefik'

  php:
    image: wodby/php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      # See all available PHP variables at https://github.com/wodby/drupal-php.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_TIMEZONE: Europe/London
      PHP_IDE_CONFIG: "serverName=drupal"       # Needed for xdebug for drush commands.
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1         # This is needed to respect remote.host setting bellow
#      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
      # - ./:/var/www/html
      # For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
      - ./web/:/var/www/html:cached # User-guided caching
      # - docker-sync:/var/www/html # Docker-sync
    networks:
      - graph

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_SERVER_ROOT: "${NGINX_SERVER_ROOT}"
    volumes:
      - ./web:/var/www/html:cached
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=$PUBLIC_PORT'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'
      - 'traefik.docker.network=traefik'
    depends_on:
      - neo4j
    networks:
      - graph
      - traefik
  
  api:
    build: ./api
    container_name: "${PROJECT_NAME}_api"
    ports:
      - 4001:4001
    volumes:
        - ./api:/app/
    environment:
      - NEO4J_URI=bolt://${PROJECT_NAME}_neo4j:${NEO4J_BOLT_PORT_NUMBER}
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - GRAPHQL_LISTEN_PORT=${GRAPHQL_LISTEN_PORT}
      - GRAPHQL_URI=http://${PROJECT_NAME}_api:4001/graphql
    labels:
      - 'traefik.backend=api'
      - 'traefik.port=${GRAPHQL_LISTEN_PORT}'
      - 'traefik.frontend.rule=Host:api.${PROJECT_BASE_URL}'
      - 'traefik.docker.network=traefik'
    depends_on:
      - neo4j
    networks:
      - graph
      - traefik


volumes:
# Docker-sync for macOS users
#  docker-sync:
#    external: true
  graph-data:
  graph-logs:
   
networks:
  traefik:
    external: true
  graph:
