version: "3"

services:
  neo4j:
    image: convivio/neo4j:$NEO4J_TAG
    container_name: "${PROJECT_NAME}_neo4j"
    volumes: 
      - graph-data:/data
    ports:
      # - '7474:7474'
      # - '7473:7473'
      - '7687:7687'
    environment:
      NEO4J_PASSWORD: $NEO4J_PASSWORD
      NEO4J_HOST: $NEO4J_HOST
      # NEO4J_BOLT_PORT_NUMBER: $NEO4J_BOLT_PORT_NUMBER
      # NEO4J_HTTP_PORT_NUMBER: $NEO4J_HTTP_PORT_NUMBER
      # NEO4J_HTTPS_PORT_NUMBER: $NEO4J_HTTPS_PORT_NUMBER
    networks:
      - neo4j-network
      - graph
      - traefik
    labels:
      - 'traefik.backend=neo4j'
      - 'traefik.port=$NEO4J_HTTP_PORT_NUMBER'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'
      - 'traefik.docker.network=traefik'

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    environment:
      NGINX_VHOST_PRESET: html
      NGINX_INDEX_FILE: index.html
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_SERVER_ROOT: "${NGINX_SERVER_ROOT}"
    volumes:
      - ./:/var/www/html:cached
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=$PUBLIC_PORT'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'
      - 'traefik.docker.network=traefik'
    networks:
      - graph
      - traefik


volumes:
# Docker-sync for macOS users
#  docker-sync:
#    external: true
  graph-data:
   
networks:
  traefik:
    external: true
  neo4j-network:
    external: true
  graph:
